version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: nest_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cp_database
    ports:
      - '5435:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: nest_cp_api
    ports:
      - '3030:3001'
    volumes:
      - .:/usr/src/app              
      - /usr/src/app/node_modules   
    depends_on:
      - db
    env_file:
      - .env
    command: npm run start:dev   

volumes:
  db_data:
